services:
  app-front:
    build:
      context: ./WebApp
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - rh-api
    networks:
      - app-network
  rh-api:
    build:
      context: ./GestaoRH
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
    - app-network
networks:
  app-network:
    driver: bridge